"""Generate a Markdown report for a fitted landmark-based registration."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a Markdown report from a fitted registration manifest and residuals CSV"
    )
    parser.add_argument("manifest_json", help="path to the fitted registration manifest JSON")
    parser.add_argument("residuals_csv", help="path to the landmark residuals CSV")
    parser.add_argument(
        "-o",
        "--output-md",
        default=None,
        help="path to the Markdown report output",
    )
    return parser


def build_report(
    manifest_payload: dict[str, object],
    residual_rows: list[dict[str, str]],
) -> str:
    registration_qc = manifest_payload.get("registration_qc", {})
    registration_provenance = manifest_payload.get("registration_provenance", {})
    top_residuals = sorted(
        residual_rows,
        key=lambda row: float(row["residual_distance_px"]),
        reverse=True,
    )[:5]

    lines = [
        "# NeuroTrace Registration Fit Report",
        "",
        "## Summary",
        "",
        f"- Image: `{manifest_payload['image_name']}`",
        f"- Atlas: `{manifest_payload['atlas_name']}`",
        f"- Method: `{registration_provenance.get('method', 'unknown')}`",
        f"- Landmark count: `{registration_qc.get('landmark_count', '')}`",
        f"- Landmark RMSE (px): `{_fmt(registration_qc.get('landmark_rmse_px'))}`",
        f"- Generated by: `{registration_provenance.get('generated_by', '')}`",
    ]

    if registration_provenance.get("notes"):
        lines.append(f"- Notes: {registration_provenance['notes']}")

    lines.extend(
        [
            "",
            "## Largest Landmark Residuals",
            "",
            "| Label | Residual (px) | Residual X | Residual Y |",
            "| --- | ---: | ---: | ---: |",
        ]
    )

    for row in top_residuals:
        lines.append(
            f"| {row.get('label') or '-'} | {float(row['residual_distance_px']):.4f} | "
            f"{float(row['residual_x_px']):.4f} | {float(row['residual_y_px']):.4f} |"
        )

    return "\n".join(lines) + "\n"


def read_manifest(path: str | Path) -> dict[str, object]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def read_residuals(path: str | Path) -> list[dict[str, str]]:
    with Path(path).open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def default_output_path(manifest_json: Path) -> Path:
    stem = manifest_json.with_suffix("")
    return stem.parent / f"{stem.name}_registration_report.md"


def main() -> None:
    args = build_parser().parse_args()
    manifest_json = Path(args.manifest_json)
    output_md = Path(args.output_md) if args.output_md else default_output_path(manifest_json)
    report = build_report(read_manifest(manifest_json), read_residuals(args.residuals_csv))
    output_md.write_text(report, encoding="utf-8")
    print(f"wrote registration report to {output_md}")


def _fmt(value: object) -> str:
    if isinstance(value, (int, float)):
        return f"{float(value):.4f}"
    return str(value)


if __name__ == "__main__":
    main()
